spring.application.name=eazystore
logging.pattern.console=%green(%d{HH:mm:ss:SSSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
spring.datasource.url=jdbc:postgresql://localhost:5432/eazystore
spring.datasource.username=postgres
spring.datasource.password=Shag1430@
spring.jpa.hibernate.ddl-auto=update